#!/bin/bash
sha1sum ida/ida/0.1/ida-0.1.pom                           > ida/ida/0.1/ida-0.1.pom.sha1
sha1sum ida/ida/0.1.1/ida-0.1.1.pom                       > ida/ida/0.1.1/ida-0.1.1.pom.sha1
sha1sum ida/ida-corelib/0.1/ida-corelib-0.1.jar           > ida/ida-corelib/0.1/ida-corelib-0.1.jar.sha1
sha1sum ida/ida-corelib/0.1/ida-corelib-0.1.pom           > ida/ida-corelib/0.1/ida-corelib-0.1.pom.sha1            
sha1sum ida/ida-corelib/0.1.1/ida-corelib-0.1.1.jar       > ida/ida-corelib/0.1.1/ida-corelib-0.1.1.jar.sha1        
sha1sum ida/ida-corelib/0.1.1/ida-corelib-0.1.1.pom       > ida/ida-corelib/0.1.1/ida-corelib-0.1.1.pom.sha1        
sha1sum ida/ida-weblib/0.1/ida-weblib-0.1.jar             > ida/ida-weblib/0.1/ida-weblib-0.1.jar.sha1              
sha1sum ida/ida-weblib/0.1/ida-weblib-0.1.pom             > ida/ida-weblib/0.1/ida-weblib-0.1.pom.sha1              
sha1sum ida/ida-weblib/0.1.1/ida-weblib-0.1.1.jar         > ida/ida-weblib/0.1.1/ida-weblib-0.1.1.jar.sha1          
sha1sum ida/ida-weblib/0.1.1/ida-weblib-0.1.1.pom         > ida/ida-weblib/0.1.1/ida-weblib-0.1.1.pom.sha1          
sha1sum ida/mesken-core/0.1/mesken-core-0.1.jar           > ida/mesken-core/0.1/mesken-core-0.1.jar.sha1            
sha1sum ida/mesken-core/0.1/mesken-core-0.1.pom           > ida/mesken-core/0.1/mesken-core-0.1.pom.sha1            
sha1sum ida/mesken-core/0.1.1/mesken-core-0.1.1.jar       > ida/mesken-core/0.1.1/mesken-core-0.1.1.jar.sha1        
sha1sum ida/mesken-core/0.1.1/mesken-core-0.1.1.pom       > ida/mesken-core/0.1.1/mesken-core-0.1.1.pom.sha1        
sha1sum ida/mesken-weblib/0.1/mesken-weblib-0.1.jar       > ida/mesken-weblib/0.1/mesken-weblib-0.1.jar.sha1        
sha1sum ida/mesken-weblib/0.1/mesken-weblib-0.1.pom       > ida/mesken-weblib/0.1/mesken-weblib-0.1.pom.sha1        
sha1sum ida/mesken-weblib/0.1.1/mesken-weblib-0.1.1.jar   > ida/mesken-weblib/0.1.1/mesken-weblib-0.1.1.jar.sha1    
sha1sum ida/mesken-weblib/0.1.1/mesken-weblib-0.1.1.pom   > ida/mesken-weblib/0.1.1/mesken-weblib-0.1.1.pom.sha1    
sha1sum wdl/org.xmdl.wdl.ida-archetype/0.1/org.xmdl.wdl.ida-archetype-0.1.jar   > wdl/org.xmdl.wdl.ida-archetype/0.1/org.xmdl.wdl.ida-archetype-0.1.jar.sha1
sha1sum wdl/org.xmdl.wdl.ida-archetype/0.1/org.xmdl.wdl.ida-archetype-0.1.pom   > wdl/org.xmdl.wdl.ida-archetype/0.1/org.xmdl.wdl.ida-archetype-0.1.pom.sha1
